[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "ease_background_colour{new_colour = G.C.BLACK, contrast = 3}"
position = "after"
match_indent = true
payload = '''

elseif G.GAME.expedition_active == true and G.GAME.expedition_key then
for k, v in pairs(G.P_BLINDS) do
    if v.key == G.GAME.expedition_key then   
        if G.GAME.blind.boss then
        ease_background_colour(v.boss_palette)
        else
        ease_background_colour(v.palette)
        end
    end
end
'''

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "ease_background_colour{new_colour = lighten(mix_colours(boss_col, G.C.BLACK, 0.3), 0.1), special_colour = boss_col, contrast = 2}"
position = "before"
match_indent = true
payload = '''
for k, v in pairs(G.P_BLINDS) do
            if v.name == blindname then
                if v.boss and not v.boss.expedition then 
               
        
'''

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "ease_background_colour{new_colour = lighten(mix_colours(boss_col, G.C.BLACK, 0.3), 0.1), special_colour = boss_col, contrast = 2}"
position = "after"
match_indent = true
payload = '''
            end
        end
    end
        
'''
